# Header
menu:
  首页: /
  分类: /categories
  友链: /links
  关于: /about

#cdn加速
#cdn: https://raw.gitmirror.com/waterkin0/images/main/
# cdn: https://waterkin0.coding.net/public/images/blogimages/git/files/main/
cdn: https://cdn.waterkin.top/https://github.com/waterkin0/images/blob/main/
#cdn: https://jsd.cdn.zzko.cn/gh/waterkin0/images@main/

# 主页背景图
background_day:  blog_base/day.jpg
background_night: blog_base/night.jpg
banner: blog_base/主页.jpg
notice: 想换个主题了，可能最近会出现显示错误啥的，还请谅解

# 作者信息
author:
  name: 水帝
  avatar: /touma2.jpg
  description: 啥也不是

toc:
  max_depth: 5 # 生成 TOC 的最大深度
  min_depth: 1 # 生成 TOC 的最小深度

comments: #评论 暂时没开
  enable: false
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: 
    appKey: 
    avatar: mm
    placeholder: 随便说点什么叭～
    notify: true
    visitor: true
    pageSize: 10
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: 
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: https://hm.baidu.com/hm.js?faa79fd1473d6ada0916813f7e10d6e9
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: /favicon.ico


# Social Icon 其他链接 可自定义 没开
social_icon:
  enable: true
  icons:
    ins     :
    zhihu   :
    weibo   : 
    github  : https://github.com/waterkin0/
    twitter : 